-- Dataverse - initial PostgreSQL schema
-- Converted & normalised from the legacy MySQL tables: main, caller_id, posts (pages is dropped: it only held legacy routing).
--
-- Design notes
--  * profiles keep integer IDs so legacy "Dataverse IDs" (relationships, links) survive the import.
--  * Legacy "0 = nobody" foreign keys become real NULL foreign keys.
--  * Legacy tinyint flags become readable, CHECK-constrained text values.
--  * Auth tables use UUIDs.
--  * Search columns are backed by pg_trgm GIN indexes so ILIKE '%partial%' stays fast on large tables.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Keeps updated_at current without relying on application code.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- profiles  (legacy: main)
-- ---------------------------------------------------------------------------
CREATE TABLE profiles (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            text NOT NULL CHECK (length(btrim(name)) > 0),
  nickname        text,
  email           text,
  phone           text,
  phone_digits    text GENERATED ALWAYS AS (regexp_replace(coalesce(phone, ''), '\D', '', 'g')) STORED,

  gender          text CHECK (gender IN ('MALE', 'FEMALE')),
  marital_status  text CHECK (marital_status IN ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED')),
  dob             date,
  blood_group     text CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
  religion        text,
  political_view  text,
  nid             text,
  occupation      text,
  education_level text,
  education_group text,
  lineage         text,           -- family / house (বংশ/বাড়ি)

  -- current address
  present_street  text,
  present_city   text,
  -- permanent address
  street          text,
  union_name      text,           -- legacy column `_union`
  sub_district    text,
  district        text,
  state           text,
  zip             text,           -- text: leading zeros and non-numeric codes are valid
  country         text,

  -- social
  facebook        text,
  instagram       text,
  tiktok          text,

  about           text,
  tags            text[] NOT NULL DEFAULT '{}',

  -- family relationships (legacy 0 => NULL)
  father_id       integer REFERENCES profiles (id) ON DELETE SET NULL,
  mother_id       integer REFERENCES profiles (id) ON DELETE SET NULL,
  spouse_id       integer REFERENCES profiles (id) ON DELETE SET NULL,

  -- photo bytes live in profile_photos; this is only a cache-busting marker (NULL => no photo)
  photo_updated_at timestamptz,

  created_by      uuid,
  updated_by      uuid,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT profiles_not_own_father CHECK (father_id IS DISTINCT FROM id),
  CONSTRAINT profiles_not_own_mother CHECK (mother_id IS DISTINCT FROM id),
  CONSTRAINT profiles_not_own_spouse CHECK (spouse_id IS DISTINCT FROM id)
);

CREATE INDEX profiles_father_idx     ON profiles (father_id) WHERE father_id IS NOT NULL;
CREATE INDEX profiles_mother_idx     ON profiles (mother_id) WHERE mother_id IS NOT NULL;
CREATE INDEX profiles_spouse_idx     ON profiles (spouse_id) WHERE spouse_id IS NOT NULL;
CREATE INDEX profiles_created_by_idx ON profiles (created_by);
CREATE INDEX profiles_district_idx   ON profiles (lower(district));
CREATE INDEX profiles_name_sort_idx  ON profiles (lower(name), id);
CREATE INDEX profiles_name_trgm_idx     ON profiles USING gin (name gin_trgm_ops);
CREATE INDEX profiles_nickname_trgm_idx ON profiles USING gin (nickname gin_trgm_ops);
CREATE INDEX profiles_email_trgm_idx    ON profiles USING gin (email gin_trgm_ops);
CREATE INDEX profiles_phone_trgm_idx    ON profiles USING gin (phone_digits gin_trgm_ops);
CREATE INDEX profiles_tags_idx          ON profiles USING gin (tags);

CREATE TRIGGER profiles_set_updated_at BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Profile photos are stored in PostgreSQL because Netlify (and most serverless hosts)
-- have no persistent file system. Images are resized client-side and capped at 1 MB by the API.
CREATE TABLE profile_photos (
  profile_id   integer PRIMARY KEY REFERENCES profiles (id) ON DELETE CASCADE,
  content_type text NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
  data         bytea NOT NULL,
  size_bytes   integer NOT NULL,
  updated_at   timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email                   text NOT NULL,
  username                text NOT NULL CHECK (username ~ '^[A-Za-z0-9_.-]{3,32}$'),
  display_name            text NOT NULL,
  password_hash           text NOT NULL,
  role                    text NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
  is_active               boolean NOT NULL DEFAULT true,
  must_change_password    boolean NOT NULL DEFAULT false,
  -- bumped on password change / deactivation / role change to invalidate issued JWTs
  token_version           integer NOT NULL DEFAULT 0,
  -- optional link between an account and "their" person profile
  profile_id              integer REFERENCES profiles (id) ON DELETE SET NULL,
  theme                   text NOT NULL DEFAULT 'system' CHECK (theme IN ('light', 'dark', 'system')),
  preferences             jsonb NOT NULL DEFAULT '{}'::jsonb,
  reset_token_hash        text,
  reset_token_expires_at  timestamptz,
  last_login_at           timestamptz,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_key    ON users (lower(email));
CREATE UNIQUE INDEX users_username_key ON users (lower(username));
CREATE INDEX users_role_idx            ON users (role);
CREATE INDEX users_profile_idx         ON users (profile_id) WHERE profile_id IS NOT NULL;
CREATE INDEX users_search_trgm_idx     ON users USING gin ((display_name || ' ' || username || ' ' || email) gin_trgm_ops);
CREATE INDEX users_reset_token_idx     ON users (reset_token_hash) WHERE reset_token_hash IS NOT NULL;

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE profiles
  ADD CONSTRAINT profiles_created_by_fk FOREIGN KEY (created_by) REFERENCES users (id) ON DELETE SET NULL,
  ADD CONSTRAINT profiles_updated_by_fk FOREIGN KEY (updated_by) REFERENCES users (id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- caller_contacts  (legacy: caller_id)
--   connection_id = the profile whose phonebook this contact came from ("relative")
--   profile_id    = the profile this number belongs to, when known
-- ---------------------------------------------------------------------------
CREATE TABLE caller_contacts (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL CHECK (length(btrim(name)) > 0),
  number        text NOT NULL CHECK (length(btrim(number)) > 0),
  number_digits text GENERATED ALWAYS AS (regexp_replace(number, '\D', '', 'g')) STORED,
  name_key      text GENERATED ALWAYS AS (lower(btrim(name))) STORED,
  connection_id integer REFERENCES profiles (id) ON DELETE SET NULL,
  profile_id    integer REFERENCES profiles (id) ON DELETE SET NULL,
  created_by    uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- The legacy README documented a manual "remove duplicates" query. This makes it a database guarantee:
-- the same name + number inside the same phonebook can only exist once.
CREATE UNIQUE INDEX caller_contacts_dedupe_key
  ON caller_contacts (COALESCE(connection_id, 0), number_digits, name_key);
CREATE INDEX caller_contacts_connection_idx ON caller_contacts (connection_id);
CREATE INDEX caller_contacts_profile_idx    ON caller_contacts (profile_id) WHERE profile_id IS NOT NULL;
CREATE INDEX caller_contacts_name_trgm_idx  ON caller_contacts USING gin (name gin_trgm_ops);
CREATE INDEX caller_contacts_digits_trgm_idx ON caller_contacts USING gin (number_digits gin_trgm_ops);
CREATE INDEX caller_contacts_name_sort_idx  ON caller_contacts (name_key, id);

CREATE TRIGGER caller_contacts_set_updated_at BEFORE UPDATE ON caller_contacts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- posts  (legacy: posts) - notes / stories attached to a profile
-- ---------------------------------------------------------------------------
CREATE TABLE posts (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id  integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  title       text NOT NULL,
  content     text NOT NULL DEFAULT '',
  status      text NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'draft', 'archived')),
  tags        text[] NOT NULL DEFAULT '{}',
  created_by  uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX posts_profile_idx ON posts (profile_id, created_at DESC);

CREATE TRIGGER posts_set_updated_at BEFORE UPDATE ON posts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- site_settings - global, admin-managed key/value configuration
-- ---------------------------------------------------------------------------
CREATE TABLE site_settings (
  key        text PRIMARY KEY,
  value      jsonb NOT NULL,
  updated_by uuid REFERENCES users (id) ON DELETE SET NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO site_settings (key, value) VALUES
  ('site_name',             '"Dataverse"'),
  ('site_description',      '"Family profiles, generation trees and a shared contact directory."'),
  ('registration_enabled',  'true'),
  ('allow_user_contributions', 'true'),
  ('default_theme',         '"system"'),
  ('contact_email',         '""')
ON CONFLICT (key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- audit_logs - append-only record of important admin actions
-- ---------------------------------------------------------------------------
CREATE TABLE audit_logs (
  id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor_id    uuid REFERENCES users (id) ON DELETE SET NULL,
  actor_label text,                  -- snapshot of who acted (survives user deletion)
  action      text NOT NULL,         -- e.g. user.create, profile.delete
  entity_type text,
  entity_id   text,
  summary     text,
  details     jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip          text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC, id DESC);
CREATE INDEX audit_logs_action_idx  ON audit_logs (action, created_at DESC);
CREATE INDEX audit_logs_actor_idx   ON audit_logs (actor_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- rate_limits - shared counter store so limits work across serverless instances
-- ---------------------------------------------------------------------------
CREATE TABLE rate_limits (
  key      text PRIMARY KEY,
  hits     integer NOT NULL DEFAULT 0,
  reset_at timestamptz NOT NULL
);

CREATE INDEX rate_limits_reset_idx ON rate_limits (reset_at);
