-- 003: entity types, multiple marriages, links between entities

-- ---- entity types: a "profile" can be a person, family, group, organization, political party or something else
ALTER TABLE profiles ADD COLUMN entity_type text NOT NULL DEFAULT 'HUMAN'
  CHECK (entity_type IN ('HUMAN', 'FAMILY', 'GROUP', 'ORGANIZATION', 'POLITICAL_PARTY', 'OTHER'));
CREATE INDEX profiles_entity_type_idx ON profiles (entity_type) WHERE entity_type <> 'HUMAN';
CREATE INDEX profiles_created_idx ON profiles (created_at DESC, id DESC);

-- ---- multiple spouses over a lifetime
-- profiles.spouse_id stays as the *current* spouse (kept in sync by the API); every marriage lives here.
CREATE TABLE marriages (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person_a   integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  person_b   integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  married_on date,
  ended_on   date,
  end_reason text CHECK (end_reason IN ('DIVORCED', 'WIDOWED', 'SEPARATED', 'OTHER')),
  note       text,
  created_by uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT marriages_ordered CHECK (person_a < person_b),
  CONSTRAINT marriages_dates   CHECK (married_on IS NULL OR ended_on IS NULL OR ended_on >= married_on)
);
CREATE UNIQUE INDEX marriages_pair_key ON marriages (person_a, person_b);
CREATE INDEX marriages_b_idx ON marriages (person_b);
CREATE TRIGGER marriages_set_updated_at BEFORE UPDATE ON marriages FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO marriages (person_a, person_b)
SELECT DISTINCT LEAST(id, spouse_id), GREATEST(id, spouse_id) FROM profiles WHERE spouse_id IS NOT NULL;

-- ---- links between any two entities (membership, sub-units, affiliations, connections)
CREATE TABLE entity_links (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_id    integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  to_id      integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  link_type  text NOT NULL CHECK (link_type IN ('MEMBER_OF', 'SUB_UNIT_OF', 'AFFILIATED_WITH', 'CONNECTED_TO')),
  role       text,          -- e.g. President, Founder, Member
  started_on date,
  ended_on   date,
  note       text,
  created_by uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT entity_links_not_self CHECK (from_id <> to_id),
  CONSTRAINT entity_links_dates    CHECK (started_on IS NULL OR ended_on IS NULL OR ended_on >= started_on)
);
CREATE UNIQUE INDEX entity_links_unique_key ON entity_links (from_id, to_id, link_type);
CREATE INDEX entity_links_to_idx ON entity_links (to_id, link_type);
CREATE TRIGGER entity_links_set_updated_at BEFORE UPDATE ON entity_links FOR EACH ROW EXECUTE FUNCTION set_updated_at();
