-- 004: separate Human and Organization entities, website field, photo-blur setting
--
--  * `profiles` now holds ONLY humans (ids unchanged, so every "Dataverse ID", family link and marriage keeps working).
--  * Everything that was a non-human profile (group / organization / political party / other / family) moves to the new
--    `organizations` table WITH THE SAME ID, together with its photo, posts, contact numbers and connections.
--  * Family entities are converted to organizations of type GROUP (nothing is deleted).
--  * Human <-> organization connections become `memberships`; organization <-> organization connections become `organization_links`.
--  * Anything that cannot be mapped (a human <-> human "connection") is kept in `entity_links_unmapped`.

-- ---- new tables ------------------------------------------------------------
CREATE TABLE organizations (
  id               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_type         text NOT NULL DEFAULT 'ORGANIZATION'
                   CHECK (org_type IN ('COMPANY', 'ORGANIZATION', 'POLITICAL_PARTY', 'GROUP', 'NGO', 'GOVERNMENT', 'EDUCATIONAL', 'OTHER')),
  name             text NOT NULL CHECK (length(btrim(name)) > 0),
  short_name       text,
  email            text,
  phone            text,
  phone_digits     text GENERATED ALWAYS AS (regexp_replace(coalesce(phone, ''), '\D', '', 'g')) STORED,
  website          text,
  founded_on       date,
  dissolved_on     date,
  -- main (registered) address
  street           text,
  union_name       text,
  sub_district     text,
  district         text,
  state            text,
  zip              text,
  country          text,
  -- office / current address
  present_street   text,
  present_city     text,
  social_links     jsonb NOT NULL DEFAULT '{}'::jsonb,
  about            text,
  tags             text[] NOT NULL DEFAULT '{}',
  photo_updated_at timestamptz,        -- logo; bytes live in organization_photos
  created_by       uuid REFERENCES users (id) ON DELETE SET NULL,
  updated_by       uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT organizations_dates CHECK (founded_on IS NULL OR dissolved_on IS NULL OR dissolved_on >= founded_on)
);
CREATE INDEX organizations_type_idx      ON organizations (org_type);
CREATE INDEX organizations_created_idx   ON organizations (created_at DESC, id DESC);
CREATE INDEX organizations_name_sort_idx ON organizations (lower(name), id);
CREATE INDEX organizations_name_trgm_idx ON organizations USING gin (name gin_trgm_ops);
CREATE INDEX organizations_tags_idx      ON organizations USING gin (tags);
CREATE TRIGGER organizations_set_updated_at BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE organization_photos (
  organization_id integer PRIMARY KEY REFERENCES organizations (id) ON DELETE CASCADE,
  content_type    text NOT NULL CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp')),
  data            bytea NOT NULL,
  size_bytes      integer NOT NULL,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- a human's membership / affiliation / connection with an organization (independent of family relationships)
CREATE TABLE memberships (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  human_id        integer NOT NULL REFERENCES profiles (id) ON DELETE CASCADE,
  organization_id integer NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  relation        text NOT NULL DEFAULT 'MEMBER' CHECK (relation IN ('MEMBER', 'AFFILIATED', 'CONNECTED')),
  role            text,
  started_on      date,
  ended_on        date,
  note            text,
  created_by      uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT memberships_dates CHECK (started_on IS NULL OR ended_on IS NULL OR ended_on >= started_on)
);
CREATE UNIQUE INDEX memberships_unique_key ON memberships (human_id, organization_id, relation);
CREATE INDEX memberships_org_idx ON memberships (organization_id, relation);
CREATE TRIGGER memberships_set_updated_at BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- organization <-> organization (sub-units, membership of a federation/party, affiliation, connection)
CREATE TABLE organization_links (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_id    integer NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  to_id      integer NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  link_type  text NOT NULL CHECK (link_type IN ('SUB_UNIT_OF', 'MEMBER_OF', 'AFFILIATED_WITH', 'CONNECTED_TO')),
  role       text,
  started_on date,
  ended_on   date,
  note       text,
  created_by uuid REFERENCES users (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT organization_links_not_self CHECK (from_id <> to_id),
  CONSTRAINT organization_links_dates    CHECK (started_on IS NULL OR ended_on IS NULL OR ended_on >= started_on)
);
CREATE UNIQUE INDEX organization_links_unique_key ON organization_links (from_id, to_id, link_type);
CREATE INDEX organization_links_to_idx ON organization_links (to_id, link_type);
CREATE TRIGGER organization_links_set_updated_at BEFORE UPDATE ON organization_links FOR EACH ROW EXECUTE FUNCTION set_updated_at();

ALTER TABLE profiles ADD COLUMN website text;

-- ---- move existing non-human profiles into organizations (same ids) -----------
INSERT INTO organizations (id, org_type, name, short_name, email, phone, founded_on, dissolved_on,
                           street, union_name, sub_district, district, state, zip, country, present_street, present_city,
                           social_links, about, tags, photo_updated_at, created_by, updated_by, created_at, updated_at)
SELECT id,
       CASE entity_type WHEN 'POLITICAL_PARTY' THEN 'POLITICAL_PARTY' WHEN 'ORGANIZATION' THEN 'ORGANIZATION'
                        WHEN 'GROUP' THEN 'GROUP' WHEN 'FAMILY' THEN 'GROUP' ELSE 'OTHER' END,
       name, nickname, email, phone, dob, date_of_death,
       street, union_name, sub_district, district, state, zip, country, present_street, present_city,
       social_links, about, tags, photo_updated_at, created_by, updated_by, created_at, updated_at
  FROM profiles WHERE entity_type <> 'HUMAN';

INSERT INTO organization_photos (organization_id, content_type, data, size_bytes, updated_at)
SELECT pp.profile_id, pp.content_type, pp.data, pp.size_bytes, pp.updated_at
  FROM profile_photos pp JOIN organizations o ON o.id = pp.profile_id;

-- ---- connections ---------------------------------------------------------------
-- human -> organization (any link type) and organization -> human (affiliation / connection) become memberships
INSERT INTO memberships (human_id, organization_id, relation, role, started_on, ended_on, note, created_by, created_at, updated_at)
SELECT CASE WHEN h.id IS NOT NULL THEN l.from_id ELSE l.to_id END,
       CASE WHEN h.id IS NOT NULL THEN l.to_id ELSE l.from_id END,
       CASE l.link_type WHEN 'MEMBER_OF' THEN 'MEMBER' WHEN 'AFFILIATED_WITH' THEN 'AFFILIATED' ELSE 'CONNECTED' END,
       l.role, l.started_on, l.ended_on, l.note, l.created_by, l.created_at, l.updated_at
  FROM entity_links l
  LEFT JOIN profiles h ON h.id = l.from_id AND h.entity_type = 'HUMAN'
  JOIN organizations o ON o.id = CASE WHEN h.id IS NOT NULL THEN l.to_id ELSE l.from_id END
 WHERE (h.id IS NOT NULL OR EXISTS (SELECT 1 FROM profiles h2 WHERE h2.id = l.to_id AND h2.entity_type = 'HUMAN'))
   AND l.link_type <> 'SUB_UNIT_OF'
ON CONFLICT DO NOTHING;

INSERT INTO organization_links (from_id, to_id, link_type, role, started_on, ended_on, note, created_by, created_at, updated_at)
SELECT l.from_id, l.to_id, l.link_type, l.role, l.started_on, l.ended_on, l.note, l.created_by, l.created_at, l.updated_at
  FROM entity_links l JOIN organizations a ON a.id = l.from_id JOIN organizations b ON b.id = l.to_id
ON CONFLICT DO NOTHING;

-- whatever is left (human <-> human "connections") is kept, not dropped
CREATE TABLE entity_links_unmapped AS
SELECT l.* FROM entity_links l
 WHERE l.from_id IN (SELECT id FROM profiles WHERE entity_type = 'HUMAN') AND l.to_id IN (SELECT id FROM profiles WHERE entity_type = 'HUMAN');
DO $$ DECLARE n integer; BEGIN
  SELECT count(*) INTO n FROM entity_links_unmapped;
  IF n > 0 THEN RAISE NOTICE '% human-to-human connection(s) were kept in table entity_links_unmapped', n; END IF;
END $$;

-- ---- posts and contact numbers that pointed at moved rows ------------------------
ALTER TABLE posts ADD COLUMN organization_id integer REFERENCES organizations (id) ON DELETE CASCADE;
ALTER TABLE posts ALTER COLUMN profile_id DROP NOT NULL;
UPDATE posts SET organization_id = profile_id, profile_id = NULL WHERE profile_id IN (SELECT id FROM organizations);
ALTER TABLE posts ADD CONSTRAINT posts_one_subject CHECK ((profile_id IS NULL) <> (organization_id IS NULL));
CREATE INDEX posts_org_idx ON posts (organization_id, created_at DESC) WHERE organization_id IS NOT NULL;

ALTER TABLE caller_contacts ADD COLUMN organization_id integer REFERENCES organizations (id) ON DELETE SET NULL;
CREATE INDEX caller_contacts_org_idx ON caller_contacts (organization_id) WHERE organization_id IS NOT NULL;
UPDATE caller_contacts SET organization_id = profile_id, profile_id = NULL WHERE profile_id IN (SELECT id FROM organizations);
-- an organization can no longer own a phonebook: detach it (dropping exact duplicates first so the unique index holds)
DELETE FROM caller_contacts c WHERE c.connection_id IN (SELECT id FROM organizations)
  AND EXISTS (SELECT 1 FROM caller_contacts d WHERE d.connection_id IS NULL AND d.number_digits = c.number_digits AND d.name_key = c.name_key);
UPDATE caller_contacts SET connection_id = NULL WHERE connection_id IN (SELECT id FROM organizations);

-- ---- humans only from now on ---------------------------------------------------
DELETE FROM profiles WHERE entity_type <> 'HUMAN';   -- photos / marriages / old links cascade (already copied above)
DROP TABLE entity_links;
DROP INDEX IF EXISTS profiles_entity_type_idx;
ALTER TABLE profiles DROP COLUMN entity_type;

SELECT setval(pg_get_serial_sequence('organizations', 'id'), GREATEST((SELECT max(id) FROM organizations), 1));

-- ---- site setting: blur female profile photos (off by default) --------------------
INSERT INTO site_settings (key, value) VALUES ('blur_female_photos', 'false') ON CONFLICT (key) DO NOTHING;
